/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'lastUpdated' : Timestamp,
  'totalVisits' : bigint,
  'pageViews' : bigint,
}
export interface Certification {
  'id' : string,
  'title' : string,
  'date' : string,
  'description' : string,
  'issuer' : string,
  'imageUrl' : string,
  'credentialUrl' : string,
}
export interface Message {
  'id' : string,
  'subject' : string,
  'name' : string,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Project {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'order' : bigint,
  'description' : string,
  'githubUrl' : string,
  'imageUrl' : string,
  'demoUrl' : string,
  'category' : string,
  'techStack' : Array<string>,
}
export interface Skill {
  'id' : string,
  'name' : string,
  'description' : string,
  'level' : bigint,
  'category' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCertification' : ActorMethod<
    [Certification],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addProject' : ActorMethod<[Project], { 'ok' : null } | { 'err' : string }>,
  'addSkill' : ActorMethod<[Skill], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chatWithAI' : ActorMethod<
    [string, Array<{ 'content' : string, 'role' : string }>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteCertification' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMessage' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteProject' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteSkill' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertifications' : ActorMethod<[], Array<Certification>>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getGithubRepos' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getGithubStats' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getResumeFileId' : ActorMethod<[], [] | [string]>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'markMessageRead' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'openAITransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'setOpenAIKey' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setResumeFileId' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'trackVisit' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCertification' : ActorMethod<
    [string, Certification],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProject' : ActorMethod<
    [string, Project],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSkill' : ActorMethod<
    [string, Skill],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];